# See config.example.yml for documentation.
object_base: orig/SB4E01
object: sys/main.dol
hash: 7d79810889824edd01c4ff02624713060a69818c
symbols: config/SB4E01/symbols.txt
splits: config/SB4E01/splits.txt
mw_comment_version: 14
ldscript_template: config/SB4E01/ldscript.lcf
